In [32]:
data = {
    'height':[1.4,1.2,1.0,1.5,1.8],
    'fav-movie': ['baby-days-out', 'the original', 'pirates of the carrebean', 'tom and jerry', 'wednesday'],
    'description': ['this movie is somehow' for i in  range(1,6)]
}

In [33]:
type(data)

dict

In [34]:
import pandas as pd
df= pd.DataFrame(data)

In [35]:
df

   height                 fav-movie            description
0     1.4             baby-days-out  this movie is somehow
1     1.2              the original  this movie is somehow
2     1.0  pirates of the carrebean  this movie is somehow
3     1.5             tom and jerry  this movie is somehow
4     1.8                 wednesday  this movie is somehow

## LABEL ENCODING

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
# 2. Initialize the LabelEncoder
le = LabelEncoder()

# 3. Fit to the column and transform text to integers
df['Encoded_Class']=le.fit_transform(df['fav-movie'])

In [38]:
df

   height                 fav-movie            description  Encoded_Class
0     1.4             baby-days-out  this movie is somehow              0
1     1.2              the original  this movie is somehow              2
2     1.0  pirates of the carrebean  this movie is somehow              1
3     1.5             tom and jerry  this movie is somehow              3
4     1.8                 wednesday  this movie is somehow              4

## one-hot encoding

In [39]:
# 2. Apply one-hot encoding and fix the dummy variable trap
# 'drop_first=True' removes the very first category column (alphabetically)
# 'dtype=int' changes the output from True/False booleans to 1/0 integers

df_encoded = pd.get_dummies(df, columns=['fav-movie'], drop_first=True, dtype=int)

In [40]:
df_encoded

,height,description,Encoded_Class,fav-movie_pirates of the carrebean,fav-movie_the original,fav-movie_tom and jerry,fav-movie_wednesday
0,1.4,this movie is somehow,0,0,0,0,0
1,1.2,this movie is somehow,2,0,1,0,0
2,1.0,this movie is somehow,1,1,0,0,0
3,1.5,this movie is somehow,3,0,0,1,0
4,1.8,this movie is somehow,4,0,0,0,1

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

# 1. Create a sample dataset with text reviews
data = {'reviews': ['the food is good',
                           'New food is terrible',
                           'good food and good services']
              }

df = pd.DataFrame(data)

# 2. Initialize the CountVectorizer
# stop_words='english' removes useless words like 'the' and 'and' to save memory
vectorizer = CountVectorizer(stop_words='english')

# 3. Fit and transform the text column 
# This learns the unique vocabulary and counts the word occurrences 
bow_matrix = vectorizer.fit_transform(df['reviews'])

# 4. Convert the matrix into a clean Pandas DataFrame
# vectorizer.get_feature_names_out() extracts the learned vocabulary as column names 

df_bow = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [ ]:
df_bow

## Tokenization

In [47]:
text = 'Deep learning is amazing!'
tokens = text.split()
print(tokens)

['Deep', 'learning', 'is', 'amazing!']

In [50]:
text = 'Deep learning is amazing!'
tokens = text.split('e')
print(tokens)

['D', '', 'p l', 'arning is amazing!']

In [51]:
import re

text = 'Deep learning is amazing!'
tokens = re.findall(r'\w+|[^\w\s]', text)

print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

## Character-level Tokenization

In [52]:
character_token = list(text)

In [54]:
print(character_token)

['D', 'e', 'e', 'p', ' ', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 'i', 's', ' ', 'a', 'm', 'a', 'z', 'i', 'n', 'g', '!']

In [106]:
with open('Tokenization.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()
len(raw_text),raw_text

(149,
 "I, am. a boy\nMessi is? the greatest. of all/ time\nI love. Barcelona, and I'm a fan?\nI love; watching; movies. in the night\nDeep -learning. is amazing")

## text cleaning using regular expression

In [107]:
import re 
white_space_splitting = re.split(r'\s', raw_text)
print(white_space_splitting)

['I,', 'am.', 'a', 'boy', 'Messi', 'is?', 'the', 'greatest.', 'of', 'all/', 'time', 'I', 'love.', 'Barcelona,', 'and', "I'm", 'a', 'fan?', 'I', 'love;', 'watching;', 'movies.', 'in', 'the', 'night', 'Deep', '-learning.', 'is', 'amazing']

In [108]:
len(white_space_splitting)

29

In [109]:
raw_text =re.sub(r'@\w+', '',raw_text, flags=re.MULTILINE)
raw_text =re.sub(r'#\w+', '', raw_text, flags=re.MULTILINE)

raw_text = re.sub(r'[^a-zA-Z\s]', '', raw_text)

print(raw_text)

I am a boy
Messi is the greatest of all time
I love Barcelona and Im a fan
I love watching movies in the night
Deep learning is amazing

In [114]:
#splitting using other criteria
white_space_splitting_with_special_xters = re.split(r'--|[@^!#*?&]|\s', raw_text)
print(white_space_splitting_with_special_xters)

['I', 'am', 'a', 'boy', 'Messi', 'is', 'the', 'greatest', 'of', 'all', 'time', 'I', 'love', 'Barcelona', 'and', 'Im', 'a', 'fan', 'I', 'love', 'watching', 'movies', 'in', 'the', 'night', 'Deep', 'learning', 'is', 'amazing']

In [115]:
#hint : use list comprehension
strip_text = [ word.strip() for word in white_space_splitting_with_special_xters if word.strip()]
len(strip_text)

29

In [116]:
print(strip_text)

['I', 'am', 'a', 'boy', 'Messi', 'is', 'the', 'greatest', 'of', 'all', 'time', 'I', 'love', 'Barcelona', 'and', 'Im', 'a', 'fan', 'I', 'love', 'watching', 'movies', 'in', 'the', 'night', 'Deep', 'learning', 'is', 'amazing']

In [117]:
#sort the text

sorted_strip_text = sorted(set(strip_text))
print(sorted_strip_text)

['Barcelona', 'Deep', 'I', 'Im', 'Messi', 'a', 'all', 'am', 'amazing', 'and', 'boy', 'fan', 'greatest', 'in', 'is', 'learning', 'love', 'movies', 'night', 'of', 'the', 'time', 'watching']

In [118]:
len(sorted_strip_text)

23

In [120]:
#enumerate keeps track 
for idx, token in enumerate(sorted_strip_text):
    print(f'({idx}, {token})')

(0, Barcelona)
(1, Deep)
(2, I)
(3, Im)
(4, Messi)
(5, a)
(6, all)
(7, am)
(8, amazing)
(9, and)
(10, boy)
(11, fan)
(12, greatest)
(13, in)
(14, is)
(15, learning)
(16, love)
(17, movies)
(18, night)
(19, of)
(20, the)
(21, time)
(22, watching)

In [121]:
# create vocabulary
vocabulary= {}
for idx, token in enumerate(sorted_strip_text):
    vocabulary[token] = idx
vocabulary

{'Barcelona': 0,
 'Deep': 1,
 'I': 2,
 'Im': 3,
 'Messi': 4,
 'a': 5,
 'all': 6,
 'am': 7,
 'amazing': 8,
 'and': 9,
 'boy': 10,
 'fan': 11,
 'greatest': 12,
 'in': 13,
 'is': 14,
 'learning': 15,
 'love': 16,
 'movies': 17,
 'night': 18,
 'of': 19,
 'the': 20,
 'time': 21,
 'watching': 22}

In [122]:
id_to_str = {}
for idx, token in enumerate(vocabulary):
    print(f'({idx}, {token})')

(0, Barcelona)
(1, Deep)
(2, I)
(3, Im)
(4, Messi)
(5, a)
(6, all)
(7, am)
(8, amazing)
(9, and)
(10, boy)
(11, fan)
(12, greatest)
(13, in)
(14, is)
(15, learning)
(16, love)
(17, movies)
(18, night)
(19, of)
(20, the)
(21, time)
(22, watching)

In [124]:
id_to_str = {}
for idx, token in enumerate(vocabulary):
    id_to_str[idx] = token
id_to_str

{0: 'Barcelona',
 1: 'Deep',
 2: 'I',
 3: 'Im',
 4: 'Messi',
 5: 'a',
 6: 'all',
 7: 'am',
 8: 'amazing',
 9: 'and',
 10: 'boy',
 11: 'fan',
 12: 'greatest',
 13: 'in',
 14: 'is',
 15: 'learning',
 16: 'love',
 17: 'movies',
 18: 'night',
 19: 'of',
 20: 'the',
 21: 'time',
 22: 'watching'}

In [126]:
token_ids = [vocabulary[word] for word  in strip_text]
print(token_ids)

[2, 7, 5, 10, 4, 14, 20, 12, 19, 6, 21, 2, 16, 0, 9, 3, 5, 11, 2, 16, 22, 17, 13, 20, 18, 1, 15, 14, 8]

In [128]:
tokens_recovered = [id_to_str[idx] for idx in token_ids]
' '.join(tokens_recovered)

'I am a boy Messi is the greatest of all time I love Barcelona and Im a fan I love watching movies in the night Deep learning is amazing'